set -sg escape-time 10
set -g base-index 1
set -g pane-base-index 1
set -g focus-events on
set -g history-limit 10000
set -g mouse on
set -s escape-time 10
set -g focus-events on
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:TC"

set -g status-position top
set -g status-justify "absolute-centre"
set -g status-style "bg=white,fg=black"
set -g status-left " #S "
set -g status-right " %H:%M "

set -g prefix C-s
unbind C-b
bind C-s send-prefix

bind r source-file ~/.tmux.conf \; display-message 'Config Reloaded'

setw -g mode-keys vi
unbind p
bind p copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'pbcopy'

bind Tab next-window
bind S-Tab previous-window

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
